import {escape as e, badge, date, schedule} from '../components/ui.js';

const heading = (eyebrow, title, description, actions = '') => `<section class="page-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div><div class="heading-actions">${actions}</div></section>`;

export function tasksPage(state) {
  const active = state.runs.filter(x => ['queued','running'].includes(x.status)).length;
  const day = new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const today = state.runs.filter(x => new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(x.created_at)) === day);
  const ok = today.filter(x => ['success','already_completed'].includes(x.status)).length;
  const failed = today.filter(x => ['failed','timeout','needs_login','needs_attention','interrupted'].includes(x.status)).length;
  const filtered = state.tasks.filter(x => (x.name+' '+x.id).toLowerCase().includes(state.search.toLowerCase()));
  return heading('AUTOMATION OVERVIEW','让日常任务，按时完成','统一管理脚本、执行计划与运行结果。', '<button class="button" data-action="discover">↻ 扫描插件</button><button class="button primary" data-action="new">＋ 新建任务</button>') +
  `<div class="stats"><article><span>任务总数</span><strong>${state.tasks.length}</strong><small>${state.tasks.filter(x=>x.enabled).length} 个定时任务已开启</small></article><article><span>正在执行 / 排队</span><strong>${active}<i class="stat-dot"></i></strong><small>最多 ${state.settings.max_parallel} 个任务并行</small></article><article><span>今日成功</span><strong>${ok}</strong><small>包含今日已完成的任务</small></article><article><span>今日需关注</span><strong class="${failed?'attention':''}">${failed}</strong><small>失败、超时或需要登录</small></article></div>
  ${!state.settings.scheduler_enabled?'<div class="notice">全局定时调度已暂停；手动运行仍然可用。</div>':''}
  <section class="panel"><div class="panel-toolbar"><div><h2>全部任务 <span class="count">${state.tasks.length}</span></h2><small>时间表使用各任务配置的时区</small></div><input class="search" id="search" placeholder="搜索任务名称或 ID" value="${e(state.search)}" aria-label="搜索任务"></div>
  <div class="batch-bar"><span>已选 <strong id="selected-count">${state.selected.size}</strong> 项</span><button class="button compact" data-action="batch-run">运行所选</button><button class="button compact" data-action="batch-enable">开启定时</button><button class="button compact" data-action="batch-disable">关闭定时</button><span class="muted batch-hint">每个任务独立执行，结果分别记录</span></div>
  <div class="table-wrap"><table><thead><tr><th class="check-cell"><input type="checkbox" id="select-all" aria-label="选择所有任务" ${filtered.length && filtered.every(x=>state.selected.has(x.id))?'checked':''}></th><th>任务</th><th>定时开关</th><th>执行频率</th><th>最近结果</th><th>下次执行</th><th>操作</th></tr></thead><tbody>${filtered.map(task=>`<tr><td><input type="checkbox" data-select="${e(task.id)}" aria-label="选择 ${e(task.name)}" ${state.selected.has(task.id)?'checked':''}></td><td><div class="task-name"><span class="task-icon ${task.id==='workbuddy'?'buddy':''}">${task.id==='workbuddy'?'W':'⌘'}</span><div><strong>${e(task.name)}</strong><small>${e(task.description||task.id)}</small></div></div></td><td><button class="switch ${task.enabled?'on':''}" role="switch" aria-checked="${task.enabled}" aria-label="${e(task.name)} 定时开关" data-action="toggle" data-id="${e(task.id)}"><span></span></button></td><td><span>${e(schedule(task))}</span><small class="cell-small">${e(task.schedule.timezone)}</small></td><td>${badge(task.last_run?.status)}</td><td class="date-cell">${task.enabled?date(task.next_run):'—'}</td><td><div class="row-actions"><button class="link-button" data-action="run" data-id="${e(task.id)}">运行</button><button class="link-button" data-action="edit" data-id="${e(task.id)}">编辑</button><button class="link-button muted" data-action="history" data-id="${e(task.id)}">记录</button><button class="icon-button delete" data-action="delete" data-id="${e(task.id)}" aria-label="删除 ${e(task.name)}">×</button></div></td></tr>`).join('') || '<tr><td colspan="7"><div class="empty">这里还没有任务。添加脚本插件，或点击「新建任务」。</div></td></tr>'}</tbody></table></div>
  <div class="panel-foot"><i class="live-dot"></i> 每 3 秒自动更新 <span>任务配置和执行记录保存在本机</span></div></section>`;
}

export function runsPage(state) {
  const runs = state.runs.filter(x=>!state.runFilter || x.task_id===state.runFilter);
  return heading('EXECUTION HISTORY','执行记录','查看每次运行的结果、耗时与日志。','<button class="button" data-action="refresh">↻ 刷新</button>') +
  `<section class="panel"><div class="panel-toolbar"><h2>最近 100 次执行</h2><select id="run-filter" aria-label="筛选任务"><option value="">全部任务</option>${state.tasks.map(x=>`<option value="${e(x.id)}" ${state.runFilter===x.id?'selected':''}>${e(x.name)}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>触发方式</th><th>开始时间</th><th>耗时 / 尝试</th><th>结果</th><th>操作</th></tr></thead><tbody>${runs.map(run=>`<tr><td><strong>${e(run.task_name)}</strong><small class="cell-small mono">${run.id.slice(0,8)}</small></td><td>${badge(run.status)}</td><td>${run.source==='schedule'?'定时':'手动'}</td><td class="date-cell">${date(run.started_at||run.created_at)}</td><td>${run.finished_at&&run.started_at?((new Date(run.finished_at)-new Date(run.started_at))/1000).toFixed(1)+' 秒':'—'}<small class="cell-small">第 ${run.attempt} 次</small></td><td class="result-cell">${e(run.message||'等待执行')}</td><td><button class="link-button" data-action="log" data-id="${run.id}">查看日志</button>${['queued','running'].includes(run.status)?`<button class="link-button attention" data-action="stop" data-id="${run.id}">停止</button>`:`<button class="link-button" data-action="run" data-id="${e(run.task_id)}">重跑</button>`}</td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">还没有执行记录。运行一个任务后，结果会出现在这里。</div></td></tr>'}</tbody></table></div></section>`;
}

export function settingsPage(state) {
  const s=state.settings;
  return heading('WORKSPACE SETTINGS','全局配置','设置调度器和任务执行的默认行为。') +
  `<section class="panel settings-panel"><form id="settings-form"><div class="section-title"><h2>执行与调度</h2><p>保存后立即应用；正在执行的任务继续使用原有配置。</p></div><div class="form-grid"><label>最大并发任务数<input name="max_parallel" type="number" min="1" max="16" value="${s.max_parallel}" required><small>共用资源组的任务仍然串行执行。</small></label><label>默认时区<input name="timezone" value="${e(s.timezone)}" required><small>用于新建任务与统计；已有任务保留各自时区。</small></label><label>重试等待时间（秒）<input name="retry_delay_seconds" type="number" min="1" max="3600" value="${s.retry_delay_seconds}" required><small>仅当插件明确标记可重试时生效。</small></label><label>日志保留天数<input name="log_retention_days" type="number" min="1" max="3650" value="${s.log_retention_days}" required><small>自动清理过期日志，执行摘要继续保留。</small></label><label class="checkbox-label"><input name="scheduler_enabled" type="checkbox" ${s.scheduler_enabled?'checked':''}>开启全局定时调度</label><label class="checkbox-label"><input name="catch_up" type="checkbox" ${s.catch_up?'checked':''}>恢复服务时补跑一次错过的任务</label></div><div class="form-footer"><span>单任务频率在任务编辑页面设置</span><button class="button primary">保存全局配置</button></div></form></section>
  <section class="info-card"><h3>后台服务的运行方式</h3><p>页面关闭后，后台服务继续执行。电脑关机期间任务暂停；服务重新启动时，根据补跑设置恢复调度。监听地址、端口和管理访问密钥在项目 .env 中配置，修改后需重启服务。</p></section>`;
}

export function environmentPage(state) {
  const env=state.environment;
  const doctor=state.doctor;
  return heading('RUNTIME & CREDENTIALS','运行环境','检查虚拟环境，并管理任务需要的环境变量。','<button class="button" data-action="doctor">检查 WorkBuddy</button>') +
  `<section class="panel runtime-panel"><h2>Python 运行环境</h2><div class="runtime-grid"><div><span>Python 版本</span><strong>${e(env.python)}</strong></div><div><span>虚拟环境</span><strong>${env.venv?'venv 已启用':'系统 Python'}</strong></div><div><span>操作系统</span><strong>${e(env.platform)}</strong></div></div><div class="runtime-path"><span>解释器</span><code>${e(env.executable)}</code></div></section>
  <section class="panel credential-panel"><div class="panel-toolbar"><div><h2>WorkBuddy 登录状态</h2><small>读取本机客户端登录文件，或使用下方环境变量</small></div>${doctor?`<span class="badge ${doctor.ready?'success':'needs_login'}"><i></i>${doctor.ready?'已检测到凭据':'需要配置'}</span>`:''}</div><p class="doctor-message">${e(doctor?.message||'点击「检查 WorkBuddy」查看当前凭据状态。')}</p>${doctor?.path?`<code class="doctor-path">${e(doctor.path)}</code>`:''}</section>
  <section class="panel"><div class="panel-toolbar"><div><h2>任务环境变量</h2><small>已保存的值只显示配置状态；空输入保留原值</small></div></div><form id="environment-form"><div class="env-list">${env.variables.map(item=>`<div class="env-row"><div><code>${e(item.name)}</code><small>${item.configured?'已配置 · '+(item.source==='local'?'本地配置':'系统环境变量'):'未配置'}</small></div><input type="password" data-env="${e(item.name)}" autocomplete="new-password" placeholder="${item.configured?'输入新值覆盖，留空保留':'输入变量值'}" aria-label="${e(item.name)}"><button type="button" class="link-button attention" data-action="env-remove" data-id="${e(item.name)}">清除本地值</button></div>`).join('')}</div><div class="env-add"><input id="env-new-name" placeholder="新变量名称，例如 CUSTOM_TOKEN" aria-label="新变量名称"><input id="env-new-value" type="password" autocomplete="new-password" placeholder="变量值" aria-label="新变量值"></div><div class="form-footer"><span>本地值优先于系统环境变量；GitHub 密钥由发布脚本单独读取</span><button class="button primary">保存环境变量</button></div></form></section>`;
}
